name: sticker_app
description: A sticker pack manager app
publish_to: 'none'
version: 1.2.0+14

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  dio: ^5.4.0
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  wechat_assets_picker: ^9.0.0
  photo_manager: ^3.9.0
  cached_network_image: ^3.3.0
  share_plus: ^10.0.0
  uuid: ^4.2.1
  permission_handler: ^11.1.0
  pointycastle: ^3.9.1
  crypto: ^3.0.6
  app_links: ^6.3.2
  gal: ^2.3.2
  receive_sharing_intent: ^1.8.0
  image: ^4.5.2
  mime: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "icon_source.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "icon_source.png"

flutter:
  uses-material-design: true
