name: sticker_app
description: A sticker pack manager app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  dio: ^5.4.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.8.3
  path_provider: ^2.1.1
  wechat_assets_picker: ^9.0.0
  file_picker: ^8.0.0
  cached_network_image: ^3.3.0
  share_plus: ^10.0.0
  uuid: ^4.2.1
  permission_handler: ^11.1.0
  pointycastle: ^3.9.1
  app_links: ^6.3.2
  gal: ^2.3.2
  ffi: ^2.1.0
  hotkey_manager: ^0.2.3
  tray_manager: ^0.5.0
  window_manager: ^0.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
